### ISSUE TITLE
Bug in Introspection type

### ISSUE THREAD

**Issue by hpinkos** [Finch-API/finch-api-python#380]
https://github.com/Finch-API/finch-api-python/blob/main/src/finch/types/introspection.py#L28

This type has `authentication_methods: AuthenticationMethods`

However, as seen in your [API documentation](https://developer.tryfinch.com/api-reference/management/introspect) example response, `authenticaton_methods` is an array

The type on the API doc on that page is also incorrect, so there may be a mistake in your open api spec file itself

**Comment by RobertCraigie** [comment]
Thanks for the report, the Finch team is working on fixing the OpenAPI spec and hopefully get an SDK update out soon.

**Comment by RobertCraigie** [comment]
This was fixed in `v0.20.6` :)
